[project]
name = "MyDocs"
version = "0.1.0"
description = "Getting Started with gRPC on Windows"
authors = [
    { name = "Thomas Hochstrasser", email = "thommyho1988@gmail.com" }
]
readme = "README.md"
requires-python = "==3.14.*"
dependencies = [
    "markdown-include<1.0",
    "mike>2,<=3.0",
    "mkdocs-material>=9.7",
    "mkdocs-material-extensions>=1,<2.0",
]

[tool.uv]
package = false

[dependency-groups]
dev = [
    "mdformat>=1.0.0",
    "mdformat-mkdocs>=5.3.0",
]
